翻译了Linux Luminarium上的hello hackers，第一次提交PR，请多多指教
hust-open-atom-club/linux101-dojo-x64 pull request #4
Opened 2024-10-09 16:39 UTC by mevinagrise

2024-10-09 16:41 UTC, mevinagrise commented
只是简单的翻译了[Linux Luminarium](https://pwn.college/dojo/linux-luminarium)上的入门项目。如果存在错误，请你指出，我及时改正

2024-10-10 00:44 UTC, mevinagrise commented
#1

2024-10-11 05:18 UTC, mudongliang commented on hello/DESCRIPTION.md
> +  在上面的例子中，主机名是 `dojo`，但在 pwn.college 中，它将来源于您正在尝试的挑战名称。
pwn.hust.college

2024-10-11 05:18 UTC, mudongliang commented on hello/DESCRIPTION.md
> +  在 pwn.college 的后续模块中，当您学习如何使用漏洞提升权限成为管理员用户时，您会看到提示符中的 `$` 变为 `#`，这表示您已经成功了！
同上

2024-10-11 05:19 UTC, mudongliang commented on hello/module.yml
> +      - An [详尽的 Bash 教程](https://bash.cyberciti.biz/guide/Main_Page).
An 不需要

2024-10-11 05:19 UTC, mudongliang requested changes
请按照 comments 进行修改

2024-10-11 10:38 UTC, mevinagrise commented
好的

2024-10-11 11:04 UTC, closed without merging